name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: gcp-curso-fullstack
  PROJECT_NUMBER: 448188991811
  REGION: us-central1
  SERVICE_NAME: gcp-node-api
  REPOSITORY: cloud-run-source-deploy
  IMAGE_PATH: gcp-node-api

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/${{ env.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: github-ci@${{ env.PROJECT_ID }}.iam.gserviceaccount.com
          export_default_credentials: true

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: '>= 450.0.0'

      - name: Configure Docker
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build and Push Image
        run: |
          IMAGE=${{ env.REGION }}-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_PATH:${{ github.sha }}
          docker build -t $IMAGE .
          docker push $IMAGE

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $SERVICE_NAME \
            --image ${{ env.REGION }}-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_PATH:${{ github.sha }} \
            --region $REGION \
            --platform managed \
            --allow-unauthenticated
